# This file contains all the important configuration details about this application/microservice

# 1. JPA -> contains all the necessary info for JPA settings of this project.
# -> Determines how Hibernate manages your database schema on application startup
        # for ex. update -> Automatically adds new columns or tables based on your entity changes

# 2. Datasource Config -> contains all the necessary info regarding your DB like its url,username,password etc.
# -> All Spring does is visits tha URl and use username & p/w provided to pass authentication and perform the asked operation on DB based on JPA settings.

# 3. Server Config -> contains configuration for our local host
# -> port :8081,8080,9000 -> tells on which port we'll host our web app(means where tomcat will listen for requests).


#App Info -> tells spring about the name of project
spring.application.name=Product-Catalog-Service


#Datasource Config
#Connection URL
spring.datasource.url=
#Database credentials
spring.datasource.username=
spring.datasource.password=


#Server Config
server.port=8080


#JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
